name: Deploy to AWS ECR

on:
  push:
    branches:
      - main  # or your deployment branch

env:
  AWS_REGION: eu-north-1
  ECR_REPOSITORY: nginx-repo
  IMAGE_TAG: latest

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push Docker image to Amazon ECR
        run: |
          docker build -t nginx-repo .
          docker tag nginx-repo:latest 876108002345.dkr.ecr.eu-north-1.amazonaws.com/nginx-repo:latest
          docker push 876108002345.dkr.ecr.eu-north-1.amazonaws.com/nginx-repo:latest
